AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: java21
    Timeout: 30
    MemorySize: 512
    SnapStart:
      ApplyOn: PublishedVersions

Resources:
  UrbaneWebAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      # CRITICAL: Path must now start with 'backend'
      CodeUri: backend/target/urbanewebapp-0.0.1-SNAPSHOT.jar

      # Standard handler for Spring Cloud Function
      Handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler

      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiGatewayEndpoint:
    Description: "API Gateway endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
